<template><section class="page-shell"><div class="page-heading"><div><p class="eyebrow">GLOBAL ADMINISTRATION</p><h1>校园 Key 全局管理</h1><p>全员 ADMIN 模式：以下操作可绕过个人 Key 上限。旧配置中的本地 Key 已停止认证。</p></div></div>
  <el-alert title="所有校园用户均拥有全局管理能力；这里不是个人数据隔离区。修改上限将影响用户自助创建。" type="warning" show-icon class="gap" />
  <el-card class="gap"><template #header><b>上限设置</b></template><div class="filter-bar"><el-input-number v-model="owner" :min="0" placeholder="用户 ID" /><el-input-number v-model="limit" :min="0" :max="10000" /><el-button @click="readLimit">查询当前值</el-button><el-button type="primary" @click="saveLimit">保存上限</el-button><el-button v-if="owner > 0" type="warning" @click="clearLimit">恢复全局默认</el-button><span class="muted">用户 ID = 0 为全局默认；其他值为个人覆盖</span></div></el-card>
  <el-card class="gap"><template #header><b>发放 Key（管理员绕过数量上限）</b></template><div class="filter-bar"><el-input-number v-model="createOwner" :min="1" /><el-input v-model="createUserId" placeholder="平台计费用户 ID" /><el-input v-model="createName" placeholder="Key 名称" /><el-button type="primary" @click="issue">发放</el-button></div><p class="muted">请核对校园用户 ID 与平台计费用户 ID 的绑定关系；不匹配的 Key 将无法认证。</p></el-card>
  <el-dialog v-model="showSecret" title="请仅此一次保存新 Key" @closed="secret = ''" width="min(580px, 94vw)" :close-on-click-modal="false"><el-input :model-value="secret" readonly><template #append><el-button @click="copy">复制</el-button></template></el-input><template #footer><el-button type="primary" @click="showSecret = false; secret = ''">已保存</el-button></template></el-dialog>
  <el-card v-loading="loading"><template #header><b>全部新体系 Key</b> · {{ rows.length }} 个</template><el-table :data="rows" empty-text="暂无新体系 Key"><el-table-column prop="ownerId" label="校园用户 ID" width="150" /><el-table-column prop="name" label="名称" min-width="150" /><el-table-column prop="keyId" label="Key ID" min-width="240" /><el-table-column prop="status" label="状态" width="120" /><el-table-column label="操作" width="190"><template #default="{ row }"><el-button link @click="toggle(row)">{{ row.status === 'ACTIVE' ? '停用' : '启用' }}</el-button><el-button link @click="rotate(row)">轮换</el-button><el-button link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table></el-card>
</section></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import request from '@/utils/request'
import type { CampusKey } from '@/api/selfService'
const rows = ref<CampusKey[]>([]), loading = ref(false), owner = ref(0), limit = ref(5)
const createOwner = ref(1), createUserId = ref(''), createName = ref(''), secret = ref(''), showSecret = ref(false)
async function load() { loading.value = true; try { rows.value = (await request.get<CampusKey[]>('/admin/campus-keys')).data } catch { ElMessage.error('加载全局 Key 失败') } finally { loading.value = false } }
async function saveLimit() { try { await ElMessageBox.confirm(`设置用户 ID ${owner.value} 的上限为 ${limit.value}？`, '确认配置'); await request.put(`/admin/campus-keys/limits/${owner.value}`, { maxKeys: limit.value }); ElMessage.success('已保存') } catch (e: any) { if (e !== 'cancel') ElMessage.error('保存失败') } }
async function readLimit() { try { const response = await request.get<{ maxKeys: number }>(`/admin/campus-keys/limits/${owner.value}`); limit.value = response.data.maxKeys; ElMessage.success('已读取当前生效上限') } catch { ElMessage.error('读取上限失败') } }
async function clearLimit() { try { await ElMessageBox.confirm(`移除用户 ${owner.value} 的覆盖上限并恢复全局默认？`, '确认恢复'); const response = await request.delete<{ maxKeys: number }>(`/admin/campus-keys/limits/${owner.value}`); limit.value = response.data.maxKeys; ElMessage.success('已恢复全局默认') } catch (e: any) { if (e !== 'cancel') ElMessage.error('恢复失败') } }
async function rotate(row: CampusKey) { try { await ElMessageBox.confirm(`轮换 ${row.name} 将使原密钥立即失效，是否继续？`, '确认轮换', { type: 'warning' }); const response = await request.post<{ secret: string }>(`/admin/campus-keys/${row.ownerId}/${row.keyId}/rotate`); secret.value = response.data.secret; showSecret.value = true; await load() } catch (e: any) { if (e !== 'cancel') ElMessage.error('轮换失败') } }
async function revoke(row: CampusKey) { try { await ElMessageBox.confirm(`永久撤销 ${row.name}？`, '危险操作', { type: 'error' }); await request.patch(`/admin/campus-keys/${row.ownerId}/${row.keyId}`, { status: 'REVOKED' }); await load() } catch (e: any) { if (e !== 'cancel') ElMessage.error('撤销失败') } }
async function issue() { try { if (!createUserId.value || !createName.value) return ElMessage.warning('请填写计费用户 ID 和名称'); await ElMessageBox.confirm(`为校园用户 ${createOwner.value} 发放 Key？请核对计费归属。`, '确认发放'); const response = await request.post<{ secret: string }>('/admin/campus-keys', { ownerId: createOwner.value, platformUserId: createUserId.value, name: createName.value }); secret.value = response.data.secret; showSecret.value = true; await load() } catch (e: any) { if (e !== 'cancel') ElMessage.error('发放失败') } }
async function copy() { try { await navigator.clipboard.writeText(secret.value); ElMessage.success('已复制') } catch { ElMessage.error('复制失败') } }
async function toggle(row: CampusKey) { try { await ElMessageBox.confirm(`确定${row.status === 'ACTIVE' ? '停用' : '启用'} ${row.name}？`, '确认状态'); await request.patch(`/admin/campus-keys/${row.ownerId}/${row.keyId}`, { status: row.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE' }); await load() } catch (e: any) { if (e !== 'cancel') ElMessage.error('操作失败') } }
onMounted(load)
</script>
