package org.unreal.modelrouter.common.dto;

/**
 * 安全事件类型枚举
 */
public enum SecurityEventType {
    // 认证相关
    AUTHENTICATION_SUCCESS,
    AUTHENTICATION_FAILURE,
    AUTHENTICATION_LOCKED,
    
    // 授权相关
    AUTHORIZATION_SUCCESS,
    AUTHORIZATION_FAILURE,
    PERMISSION_DENIED,
    
    // 令牌相关
    TOKEN_ISSUED,
    TOKEN_REFRESHED,
    TOKEN_REVOKED,
    TOKEN_EXPIRED,
    TOKEN_VALIDATION_FAILED,
    
    // API Key相关
    API_KEY_CREATED,
    API_KEY_USED,
    API_KEY_REVOKED,
    API_KEY_EXPIRED,
    API_KEY_VALIDATION_FAILED,
    
    // 安全威胁
    BRUTE_FORCE_ATTACK,
    SUSPICIOUS_LOGIN,
    MULTIPLE_FAILED_ATTEMPTS,
    UNUSUAL_ACCESS_PATTERN,
    
    // 系统安全
    SECURITY_CONFIGURATION_CHANGED,
    SECURITY_POLICY_VIOLATION,
    DATA_BREACH_ATTEMPT,
    UNAUTHORIZED_ACCESS_ATTEMPT
}